In [19]:
import pandas as pd
import numpy as np
import seaborn as sns

In [34]:
df = pd.read_csv('informacion_campana_bancaria_2026.csv')
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,single,basic.9y,no,yes,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,yes
1,58,retired,married,professional.course,no,yes,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.970,5228.1,no
2,48,technician,married,professional.course,no,yes,yes,cellular,nov,fri,...,3,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
3,39,blue-collar,single,basic.9y,no,yes,no,cellular,apr,thu,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.483,5099.1,no
4,56,services,married,basic.4y,NaN,no,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41383,21,unemployed,married,high.school,no,yes,yes,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
41384,24,blue-collar,single,basic.9y,no,yes,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
41385,21,student,single,basic.4y,no,no,no,cellular,mar,mon,...,2,999,0,nonexistent,-1.8,92.843,-50.0,1.520,5099.1,no
41386,52,admin.,married,high.school,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
41387,40,services,married,basic.6y,no,no,no,cellular,nov,thu,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41388 entries, 0 to 41387
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41388 non-null  int64
 1   job             41054 non-null  str
 2   marital         41307 non-null  str
 3   education       39644 non-null  str
 4   default         32743 non-null  str
 5   housing         40392 non-null  str
 6   loan            40392 non-null  str
 7   contact         41388 non-null  str
 8   month           41388 non-null  str
 9   day_of_week     41388 non-null  str
 10  duration        41388 non-null  int64
 11  campaign        41388 non-null  int64
 12  pdays           41388 non-null  int64
 13  previous        41388 non-null  int64
 14  poutcome        41388 non-null  str
 15  emp.var.rate    41388 non-null  float64
 16  cons.price.idx  41388 non-null  float64
 17  cons.conf.idx   41388 non-null  float64
 18  euribor3m       41388 non-null  float64
 19  nr.employed     41388 non-null  float64
 20  y               41388 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 6.6 MB

In [23]:
(df.isnull().sum()/df.shape[0])*100

age                0.000000
job                0.806997
marital            0.195709
education          4.213782
default           20.887697
housing            2.406495
loan               2.406495
contact            0.000000
month              0.000000
day_of_week        0.000000
duration           0.000000
campaign           0.000000
pdays              0.000000
previous           0.000000
poutcome           0.000000
emp.var.rate       0.000000
cons.price.idx     0.000000
cons.conf.idx      0.000000
euribor3m          0.000000
nr.employed        0.000000
y                  0.000000
dtype: float64

In [24]:
df.duplicated().sum()

np.int64(12)

In [25]:
df[df.duplicated()]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
6838,35,admin.,married,university.degree,no,yes,no,cellular,may,fri,...,4,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
9976,47,technician,divorced,high.school,no,yes,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
19829,55,services,married,high.school,NaN,no,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
22582,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
22626,27,technician,single,professional.course,no,no,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
24813,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,no
24973,39,blue-collar,married,basic.6y,no,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
34832,32,technician,single,professional.course,no,yes,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
36112,71,retired,single,university.degree,no,no,no,telephone,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,no
39908,45,admin.,married,university.degree,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,-2.9,92.469,-33.6,1.072,5076.2,yes
40229,36,retired,married,NaN,no,no,no,telephone,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,no
41123,24,services,single,high.school,no,yes,no,cellular,apr,tue,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,no

In [26]:
# Mostrar registros completamente duplicados
duplicados = df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())

print(f"Total de filas duplicadas: {df.duplicated().sum()}")
print(f"Filas que aparecen como duplicadas (todas las copias): {len(duplicados)}\n")

duplicados

Total de filas duplicadas: 12
Filas que aparecen como duplicadas (todas las copias): 24

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
23793,24,services,single,high.school,no,yes,no,cellular,apr,tue,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,no
41123,24,services,single,high.school,no,yes,no,cellular,apr,tue,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,no
2168,27,technician,single,professional.course,no,no,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
22626,27,technician,single,professional.course,no,no,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
26139,32,technician,single,professional.course,no,yes,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
34832,32,technician,single,professional.course,no,yes,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
4049,35,admin.,married,university.degree,no,yes,no,cellular,may,fri,...,4,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
6838,35,admin.,married,university.degree,no,yes,no,cellular,may,fri,...,4,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
24943,36,retired,married,NaN,no,no,no,telephone,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,no
40229,36,retired,married,NaN,no,no,no,telephone,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,no
4038,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,no
24813,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,no
18417,39,blue-collar,married,basic.6y,no,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
24973,39,blue-collar,married,basic.6y,no,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2831,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
22582,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
13669,45,admin.,married,university.degree,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,-2.9,92.469,-33.6,1.072,5076.2,yes
39908,45,admin.,married,university.degree,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,-2.9,92.469,-33.6,1.072,5076.2,yes
4265,47,technician,divorced,high.school,no,yes,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9976,47,technician,divorced,high.school,no,yes,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
12095,55,services,married,high.school,NaN,no,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
19829,55,services,married,high.school,NaN,no,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
25699,71,retired,single,university.degree,no,no,no,telephone,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,no
36112,71,retired,single,university.degree,no,no,no,telephone,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,no

In [42]:
df_rev.info()

<class 'pandas.DataFrame'>
Index: 41376 entries, 0 to 41387
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41376 non-null  int64
 1   job             41042 non-null  str
 2   marital         41295 non-null  str
 3   education       39633 non-null  str
 4   default         32732 non-null  str
 5   housing         40380 non-null  str
 6   loan            40380 non-null  str
 7   contact         41376 non-null  str
 8   month           41376 non-null  str
 9   day_of_week     41376 non-null  str
 10  duration        41376 non-null  int64
 11  campaign        41376 non-null  int64
 12  pdays           41376 non-null  int64
 13  previous        41376 non-null  int64
 14  poutcome        41376 non-null  str
 15  emp.var.rate    41376 non-null  float64
 16  cons.price.idx  41376 non-null  float64
 17  cons.conf.idx   41376 non-null  float64
 18  euribor3m       41376 non-null  float64
 19  nr.employed     41376 non-null  float64
 20  y               41376 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 6.9 MB

In [27]:
df_rev = df.drop_duplicates()
df_rev

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,single,basic.9y,no,yes,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,yes
1,58,retired,married,professional.course,no,yes,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.970,5228.1,no
2,48,technician,married,professional.course,no,yes,yes,cellular,nov,fri,...,3,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
3,39,blue-collar,single,basic.9y,no,yes,no,cellular,apr,thu,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.483,5099.1,no
4,56,services,married,basic.4y,NaN,no,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41383,21,unemployed,married,high.school,no,yes,yes,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
41384,24,blue-collar,single,basic.9y,no,yes,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
41385,21,student,single,basic.4y,no,no,no,cellular,mar,mon,...,2,999,0,nonexistent,-1.8,92.843,-50.0,1.520,5099.1,no
41386,52,admin.,married,high.school,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
41387,40,services,married,basic.6y,no,no,no,cellular,nov,thu,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no

In [47]:
df_rev

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,single,basic.9y,no,yes,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,yes
1,58,retired,married,professional.course,no,yes,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.970,5228.1,no
2,48,technician,married,professional.course,no,yes,yes,cellular,nov,fri,...,3,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
3,39,blue-collar,single,basic.9y,no,yes,no,cellular,apr,thu,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.483,5099.1,no
4,56,services,married,basic.4y,NaN,no,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41383,21,unemployed,married,high.school,no,yes,yes,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
41384,24,blue-collar,single,basic.9y,no,yes,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
41385,21,student,single,basic.4y,no,no,no,cellular,mar,mon,...,2,999,0,nonexistent,-1.8,92.843,-50.0,1.520,5099.1,no
41386,52,admin.,married,high.school,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
41387,40,services,married,basic.6y,no,no,no,cellular,nov,thu,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no

In [46]:
df_rev['education'].value_counts()

education
university.degree      12228
high.school             9555
basic.9y                6068
professional.course     5263
basic.4y                4203
basic.6y                2298
illiterate                18
Name: count, dtype: int64

In [28]:
# Registros con 'default' nulo
df_default_nulo = df_rev[df_rev['default'].isna()]

print(f"Total registros con 'default' nulo: {len(df_default_nulo)}")
print(f"Representan el {len(df_default_nulo)/len(df_rev)*100:.2f}% del dataset\n")

# Relación con otras variables categóricas
for col in ['job', 'marital', 'education', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']:
    print(f"--- {col} ---")
    print(df_default_nulo[col].value_counts().to_string())
    print()

Total registros con 'default' nulo: 8644
Representan el 20.89% del dataset

--- job ---
job
blue-collar      3181
admin.           1305
technician        982
services          920
management        459
retired           396
housemaid         319
entrepreneur      303
self-employed     284
unemployed        237
student           104

--- marital ---
marital
married     6301
single      1493
divorced     838

--- education ---
education
basic.4y               1712
basic.9y               1631
high.school            1617
university.degree      1460
basic.6y                854
professional.course     810
illiterate                7

--- housing ---
housing
yes    4386
no     4028

--- loan ---
loan
no     7134
yes    1280

--- contact ---
contact
cellular     4390
telephone    4254

--- month ---
month
may    3429
jul    1744
jun    1397
aug    1245
nov     427
apr     349
oct      19
mar      16
sep      12
dec       6

--- poutcome ---
poutcome
nonexistent    8060
failure         524
success          60

--- y ---
y
no     8199
yes     445

In [29]:
# Relación con otras variables categóricas en porcentaje
for col in ['job', 'marital', 'education', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']:
    print(f"--- {col} ---")
    print(((df_default_nulo[col].value_counts()/df_default_nulo.shape[0])*100).round(2))
    print()

--- job ---
job
blue-collar      36.80
admin.           15.10
technician       11.36
services         10.64
management        5.31
retired           4.58
housemaid         3.69
entrepreneur      3.51
self-employed     3.29
unemployed        2.74
student           1.20
Name: count, dtype: float64

--- marital ---
marital
married     72.89
single      17.27
divorced     9.69
Name: count, dtype: float64

--- education ---
education
basic.4y               19.81
basic.9y               18.87
high.school            18.71
university.degree      16.89
basic.6y                9.88
professional.course     9.37
illiterate              0.08
Name: count, dtype: float64

--- housing ---
housing
yes    50.74
no     46.60
Name: count, dtype: float64

--- loan ---
loan
no     82.53
yes    14.81
Name: count, dtype: float64

--- contact ---
contact
cellular     50.79
telephone    49.21
Name: count, dtype: float64

--- month ---
month
may    39.67
jul    20.18
jun    16.16
aug    14.40
nov     4.94
apr     4.04
oct     0.22
mar     0.19
sep     0.14
dec     0.07
Name: count, dtype: float64

--- poutcome ---
poutcome
nonexistent    93.24
failure         6.06
success         0.69
Name: count, dtype: float64

--- y ---
y
no     94.85
yes     5.15
Name: count, dtype: float64

In [30]:
blue_collar = df_rev[df_rev['job'] == 'blue-collar']
blue_collar['default'].value_counts()

default
no    6113
Name: count, dtype: int64

In [38]:
df_rev.describe().round(2)

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41376.00,41376.00,41376.00,41376.00,41376.00,41376.00,41376.00,41376.00,41376.00,41376.00
mean,40.03,257.07,2.57,962.50,0.17,0.08,93.58,-40.50,3.62,5167.04
std,10.42,259.30,2.78,186.86,0.49,1.57,0.58,4.63,1.73,72.24
min,17.00,0.00,1.00,0.00,0.00,-3.40,92.20,-50.80,0.63,4963.60
25%,32.00,101.00,1.00,999.00,0.00,-1.80,93.08,-42.70,1.34,5099.10
50%,38.00,179.00,2.00,999.00,0.00,1.10,93.75,-41.80,4.86,5191.00
75%,47.00,318.00,3.00,999.00,0.00,1.40,93.99,-36.40,4.96,5228.10
max,98.00,4918.00,56.00,999.00,7.00,1.40,94.77,-26.90,5.04,5228.10

In [32]:
# Matriz de conteo de 'default' respecto a cada campo categórico
cols_categoricas = ['job', 'marital', 'education', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

for col in cols_categoricas:
    matriz = pd.crosstab(
        df_rev[col],
        df_rev['default'].fillna('null'),
        margins=True,
        margins_name='Total'
    )
    print(f"\n{'='*50}")
    print(f"  default  vs  {col}")
    print(f"{'='*50}")
    display(matriz)

==================================================
  default  vs  job
==================================================

default           no  null  yes  Total
job
admin.          9178  1305    0  10483
blue-collar     6113  3181    0   9294
entrepreneur    1160   303    0   1463
housemaid        746   319    0   1065
management      2474   459    0   2933
retired         1330   396    0   1726
self-employed   1143   284    0   1427
services        3059   920    0   3979
student          774   104    0    878
technician      5792   982    2   6776
unemployed       780   237    1   1018
Total          32549  8490    3  41042

==================================================
  default  vs  marital
==================================================

default      no  null  yes  Total
marital
divorced   3796   838    0   4634
married   18732  6301    3  25036
single    10132  1493    0  11625
Total     32660  8632    3  41295

==================================================
  default  vs  education
==================================================

default                 no  null  yes  Total
education
basic.4y              2491  1712    0   4203
basic.6y              1444   854    0   2298
basic.9y              4437  1631    0   6068
high.school           7937  1617    1   9555
illiterate              11     7    0     18
professional.course   4451   810    2   5263
university.degree    10768  1460    0  12228
Total                31539  8091    3  39633

==================================================
  default  vs  housing
==================================================

default     no  null  yes  Total
housing
no       14675  4028    2  18705
yes      17288  4386    1  21675
Total    31963  8414    3  40380

==================================================
  default  vs  loan
==================================================

default     no  null  yes  Total
loan
no       26969  7134    3  34106
yes       4994  1280    0   6274
Total    31963  8414    3  40380

==================================================
  default  vs  contact
==================================================

default       no  null  yes  Total
contact
cellular   21867  4390    3  26260
telephone  10862  4254    0  15116
Total      32729  8644    3  41376

==================================================
  default  vs  month
==================================================

default     no  null  yes  Total
month
apr       2291   349    0   2640
aug       4958  1245    2   6205
dec        176     6    0    182
jul       5454  1744    0   7198
jun       3949  1397    0   5346
mar        534    16    0    550
may      10414  3429    0  13843
nov       3690   427    1   4118
oct        701    19    0    720
sep        562    12    0    574
Total    32729  8644    3  41376

==================================================
  default  vs  poutcome
==================================================

default         no  null  yes  Total
poutcome
failure       3745   524    1   4270
nonexistent  27665  8060    2  35727
success       1319    60    0   1379
Total        32729  8644    3  41376

==================================================
  default  vs  y
==================================================

default     no  null  yes  Total
y
no       28510  8199    3  36712
yes       4219   445    0   4664
Total    32729  8644    3  41376